### ISSUE TITLE
Step 18/20 : COPY --from=builder /tikv/target/release/tikv-service-server /tikv-service-server COPY failed: stat tikv/target/release/tikv-service-server: file does not exist

### ISSUE THREAD

**Issue by callmeadi** [tidb-incubator/tidis#83]
Trying to create Docker image using the latest repo but it fails with error:
Step 18/20 : COPY --from=builder /tikv/target/release/tikv-service-server /tikv-service-server
COPY failed: stat tikv/target/release/tikv-service-server: file does not exist 

The file is not present in  the repo, Any suggestions ?

**Comment by yongman** [comment]
Thanks for your report. The docker file seems like stale and shlod update

**Comment by yongman** [comment]
Already fixed in https://github.com/tidb-incubator/tidis/pull/84 .
