### ISSUE TITLE
Which version of tikv is recommended to use?

### ISSUE THREAD

**Issue by in-han** [tidb-incubator/tidis#92]
I would like to know which version of tikv the performance test was run on.

For my tests, I used tikv 5.3.0 but found that after writing a lot of data, the store size remained around 10GB and didn't grow anymore.
Therefore, I suspect that tidis will not work well on tikv 5.3.0.

**Comment by yongman** [comment]
`v6.1.0` or newer version are recommended.

**Comment by in-han** [comment]
Thanks, I will try on version v6.1.0.
