### ISSUE TITLE
What does the inner_txn field means in Handler?

### ISSUE THREAD

**Issue by Praying** [tidb-incubator/tidis#93]
```rust
    /// The txn state of this connection.
    inner_txn: bool
```
 I can't understand the txt state's meaning?

**Comment by yongman** [comment]
This is a flag to indicate if the context is a global transaction, such as `EVAL/EVALSHA` or `MULT/EXEC` commands.

**Comment by Praying** [comment]
> This is a flag to indicate if the context is a global transaction, such as `EVAL/EVALSHA` or `MULT/EXEC` commands.

got it, thanks
